CREATE TABLE IF NOT EXISTS dm_my_problems (
    dm_mp INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    problem BLOB NOT NULL COMMENT 'encrypted limiting belief',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dm_my_opposites (
    dm_mo INT AUTO_INCREMENT PRIMARY KEY,
    dm_mp INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    opposite BLOB NOT NULL COMMENT 'encrypted empowering belief',
    UNIQUE KEY unique_problem (dm_mp),
    FOREIGN KEY (dm_mp) REFERENCES dm_my_problems(dm_mp) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dm_my_evidence (
    dm_me INT AUTO_INCREMENT PRIMARY KEY,
    dm_mo INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    evidence BLOB NOT NULL COMMENT 'encrypted proof the opposite is true',
    FOREIGN KEY (dm_mo) REFERENCES dm_my_opposites(dm_mo) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
